### ISSUE TITLE
New release with parallel Ascent

### ISSUE THREAD

**Issue by langston-barrett** [s-arash/ascent#17]
Looks like parallel Ascent has been merged to the main branch. It would be great to have this feature available in a release on crates.io!

**Comment by s-arash** [comment]
I'll do that soon-ish. The usual caveat that v0.6 won't be fully backwards compatible with v0.5 applies (more strongly than usual).

**Comment by s-arash** [comment]
Version `0.5.0` with parallel support has been released!
