### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by kliramu** [s-arash/ascent#37]
This is a wonderful project and deserves to be an industry standard. Please provide an explicit license.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by regexident** [comment]
The individual crates' `Cargo.toml` files specify 

```toml
[package]
...
license = "MIT"
```

https://github.com/search?q=repo%3As-arash%2Fascent%20license&type=code

But having a top-level `LICENSE` file would be appreciated, indeed.

I've opened a PR adding such a file with #38.
