### ISSUE TITLE
WASM compatibility: `std::time`

### ISSUE THREAD

**Issue by robert-chiniquy** [s-arash/ascent#4]
The very minimal use of `std::time` in Ascent unfortunately panics on WASM. 

Possible fixes include either a feature flag to gate use of `std::time` (this is only slightly complicated by `run_timeout`), or using an alternative library which provides a WASM-safe implementation such as https://github.com/sebcrozet/instant. 

Just a thought. If you would prefer a PR for one or the other of these options, let me know. Thanks!

**Comment by s-arash** [comment]
Let me take a look at this. The crate looks small enough that I'm comfortable adding it as a dependency.

**Comment by s-arash** [comment]
@robert-chiniquy I've followed your suggestion and used the `instant` crate to get around `std::time` not working on WASM. If you could take a look and let me know if it works for your wasm environment, I'd appreciate it.

**Comment by robert-chiniquy** [comment]
This works great for me, thank you!
