### ISSUE TITLE
How can I represent this problem in ascent ?

### ISSUE THREAD

**Issue by lMINERl** [s-arash/ascent#46]
I just need someone to help me or direct me on how can I represent this problem and print every step
also how backtracking works is it like (prolog?)

thanks in advance for your help and time. 

 [https://en.wikipedia.org/wiki/Wolf,_goat_and_cabbage_problem](url) 
 
problem:
a farmer / wolf / sheep / cabbage need to cross the river (East to West) coast with all of them on a 1 boat that carries 2 at max

if farmer is not around:
wolf can eat sheep 
sheep can eat cabbage 

only farmer can sail a boat.

**Comment by kmicinski** [comment]
In general, you can't do backtracking in Datalog--Datalog is chain-forward, and there's no ability to forget information, which means that to the degree you want to backtrack, you're destined to space overhead. So the answer in the purest terms is just that Datalog is intentionally simpler than Prolog, specifically lacking backtracking.

That being said, in specific cases, you can often use Ascent's lattices to mimic the backtracking-type features. Lattice updates have to form monotonically-well-ordered chains, to ensure that you are always ascending up a lattice and making progress.

I recommend you look into lattices or--if you need full backtracking--maybe Datalog isn't the best fit for your problem and you genuinely need to use a Prolog engine.
