### ISSUE TITLE
Use of magic set optimization?

### ISSUE THREAD

**Issue by regexident** [s-arash/ascent#47]
From a look at the implementation and accompanying scientific papers it seems as if `ascent` does not make use of the popular [magic sets](https://arxiv.org/abs/1204.6346) optimization for semi-naïve bottom-up implementations. At least I couldn't find any code that looks like it, nor find any mention of `magic` or `adorn` in the actual source code or the accompanying scientific papers.

The lack of explicit `input`/`output` relation declarations makes me further assume it doesn't use magic sets (as these would define the wells/sinks of the program implicit dependency graph and could thus guide the optimization)?

@s-arash @kmicinski Is this optimization something that's planned/feasible for ascent with its lattices?

Either way it would probably make sense to discoverably document whether or not it currently uses said optimization.

**Comment by s-arash** [comment]
Thanks for the opening the issue. Ascent doesn't currently do magic set transformations.

**Comment by kmicinski** [comment]
I agree with this decision. Magic sets is more relevant in the case where you’re using Datalog  in a querying-based setting. If you plan to materialize everything and inspect the result of a fixed point, it’s less relevant since you’d end up materializing everything anyway..
